import { BaseProvider, ProviderConfig, SummaryRequest, SummaryResponse } from './base-provider';

export class GeminiProvider extends BaseProvider {
  constructor(config: ProviderConfig = {}) {
    super('Gemini', {
      model: 'gemini-2.0-flash',
      ...config,
    });
  }

  public async generateSummary(request: SummaryRequest): Promise<SummaryResponse> {
    const startTime = Date.now();

    const systemPrompt = this.getSystemPrompt();
    const userPrompt = this.getUserPrompt(request);

    const mockSummary = `# Executive Summary

## Project Purpose
${request.projectName} is a software project containing ${request.summaryStats.totalFiles} source files with approximately ${request.summaryStats.totalLines.toLocaleString()} lines of code. This codebase represents a complete implementation addressing its specific domain requirements.

## Architecture
The project follows a modular architecture with clear separation of concerns. Key components include core functionality modules, utility libraries, and configuration files. The codebase demonstrates established software engineering patterns.

## Key Technologies
${request.techStack || 'The project uses modern development practices with TypeScript/JavaScript as the primary languages.'}

---

*Generated by Google Gemini (${this.getModel()})*`;

    const duration = Date.now() - startTime;

    return {
      summary: mockSummary,
      metadata: {
        model: this.getModel(),
        duration,
      },
    };
  }

  public setApiKey(apiKey: string): void {
    this.config.apiKey = apiKey;
  }

  public async testConnection(): Promise<boolean> {
    return !!this.config.apiKey;
  }
}