import { BaseProvider, ProviderConfig, SummaryRequest, SummaryResponse } from './base-provider';

export class GroqProvider extends BaseProvider {
  constructor(config: ProviderConfig = {}) {
    super('Groq', {
      model: 'mixtral-8x7b-32768',
      ...config,
    });
  }

  public async generateSummary(request: SummaryRequest): Promise<SummaryResponse> {
    const startTime = Date.now();

    const mockSummary = `# Executive Summary

## Project Purpose
${request.projectName} is a software project containing ${request.summaryStats.totalFiles} source files with approximately ${request.summaryStats.totalLines.toLocaleString()} lines of code. This codebase provides a comprehensive solution for its intended use case.

## Architecture
The project follows industry-standard architecture patterns with clear separation between core logic, utilities, and configuration. Code is organized in a maintainable structure that promotes reusability and testability.

## Key Technologies
${request.techStack || 'The project leverages modern development frameworks and tools. TypeScript/JavaScript provides type safety and developer productivity.'}

---

*Generated by Groq (${this.getModel()}) - Ultra-fast AI inference*`;

    const duration = Date.now() - startTime;

    return {
      summary: mockSummary,
      metadata: {
        model: this.getModel(),
        duration,
      },
    };
  }

  public setApiKey(apiKey: string): void {
    this.config.apiKey = apiKey;
  }

  public async testConnection(): Promise<boolean> {
    return !!this.config.apiKey;
  }
}