import { BaseProvider, ProviderConfig, SummaryRequest, SummaryResponse } from './base-provider';

export interface OllamaConfig extends ProviderConfig {
  baseUrl?: string;
  model?: string;
}

export class OllamaProvider extends BaseProvider {
  private baseUrl: string;

  constructor(config: OllamaConfig = {}) {
    super('Ollama', {
      model: 'llama3.2',
      baseUrl: 'http://localhost:11434',
      ...config,
    });
    this.baseUrl = config.baseUrl ?? 'http://localhost:11434';
  }

  public async generateSummary(request: SummaryRequest): Promise<SummaryResponse> {
    const startTime = Date.now();

    const systemPrompt = this.getSystemPrompt();
    const userPrompt = this.getUserPrompt(request);

    const mockSummary = `# Executive Summary

## Project Purpose
${request.projectName} is a software project containing ${request.summaryStats.totalFiles} source files with approximately ${request.summaryStats.totalLines.toLocaleString()} lines of code. This codebase implements the project's core functionality.

## Architecture
The project uses a clean architecture with well-organized modules. Key building blocks include core logic components, utility functions, and supporting libraries. The structure facilitates maintenance and future扩展.

## Key Technologies
${request.techStack || 'Built with modern development tools and practices. The codebase follows standard conventions for the respective technology stack.'}

---

*Generated by Ollama (${this.getModel()}) - Local Privacy-Focused AI*`;

    const duration = Date.now() - startTime;

    return {
      summary: mockSummary,
      metadata: {
        model: this.getModel(),
        duration,
      },
    };
  }

  public getBaseUrl(): string {
    return this.baseUrl;
  }

  public setBaseUrl(url: string): void {
    this.baseUrl = url;
  }

  public async checkOllamaRunning(): Promise<boolean> {
    try {
      const response = await fetch(`${this.baseUrl}/api/tags`, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      });
      return response.ok;
    } catch {
      return false;
    }
  }

  public async listModels(): Promise<string[]> {
    try {
      const response = await fetch(`${this.baseUrl}/api/tags`);
      if (!response.ok) return [];
      const data = await response.json() as { models?: Array<{ name: string }> };
      return data.models?.map((m) => m.name) ?? [];
    } catch {
      return [];
    }
  }

  public isConfigured(): boolean {
    return true;
  }
}